### ISSUE TITLE
Problems with reimporting edited raw text files

### ISSUE THREAD

**Issue by webfischi** [DerPopo/UABE#109]
Reimporting Text Files with more than 3 Million ANSI charackters is impossible, because the program is writing the rest of the script into string m_PathName. First I thought the Japanese translation of the game is a problem, but after deleting the whole Japanese line creating this problem, it is doing the same with the Spanish translation one line below.
UABE startet to this the first time after exact 2.916.335 ANSI charackters, the last time at 2.916.596. But importing the original is working flawlessly. Could this be a problem with the file size? The new file is 24KB larger than the original file. I modded the game multiple times before with UAE but it doesn't support Unity 5.5 (and never will). The games don't care about the text file size. And the dumps of the text files are looking weird, too. The last character is always \r instead of the letter or the symbol.
The Game I have problems with, is 60 Seconds! Hope this will be fixed soon. Keep up the good work.

**Comment by webfischi** [comment]
Changed the topic name, to hopefully get an answer. In case you didn't understand what I tried to say, I can do it in german as well, according to your name you are able understanding the german language.

**Comment by DerPopo** [comment]
I'm unable to reproduce this, even with a 75MB file using the TextAsset plugin.
In case you're using raw import, it creates weird behaviour because the TextAsset format isn't just a raw data format. Each string in Unity contains a length field which isn't automatically updated on a raw import (else it would have to guess where which string starts). If the actual string size exceeds that length, it overwrites the length value of the next string with unrelated data. You either have to update the length field manually or simply use the plugin.
The line endings in the dump are converted to their C-style escape sequences so the strings stay in one line. Each new line ends the previous field, so multiline strings would just cause issues.

**Comment by webfischi** [comment]
Can you tell me how to update the length field manually?

**Comment by DerPopo** [comment]
You'll need to open it in a hex editor such as HxD, calculate the length of the text that should appear in m_Script in hexadecimal (calc in programmer mode can help) and put it in reversed byte order (e.g. 1A2B3C4D will be 4D3C2B1A in the length field). The length is a 4 byte value immediately before the text. The text must end aligned to 4 bytes, i.e. 00 has to be appended after the text using the hex editor up to three times so the file length is divisible by 4. The alignment 00s don't effect the length value.

**Comment by webfischi** [comment]
The text import export for unity 5.5 is way more bugged than expected, I changed one letter from the raw file, which shouldn't be a problem, I still get a pink screen and more important, I can't reopen the modified asset file. At least, thanks to your tip, everything is imported correctly, but saved asset file is always broken.

**Comment by DerPopo** [comment]
Do you have sample files where a raw import causes the file to be broken? I've fixed a bug like this in 2.1b and it seemed fine then.

**Comment by webfischi** [comment]
The problem occurs when I export the book.txt from sharedassets0.assets change one letter in the exported .dat file, reimport the exported .dat file and save the asset. When I try to open the saved asset file, UABE is not responding and I have to force quit it.

I'm Using UABE 2.1c, the game is Unity 5.5.0.46319

**Comment by DerPopo** [comment]
Try the plugin to export to .txt / to import from .txt. It sounds like the binary data in the TextAsset were damaged while editing, which some programs like notepad do to binary files.

**Comment by webfischi** [comment]
Still getting the same errors, can't reopen saved asset, and I'll get just a pink screen on game start. But now I know how to export and import txt files.

**Comment by DerPopo** [comment]
Do you have a sample file that causes these issues? In case it's too big, maybe you can also use another .assets file with issues when reimporting changed assets (raw export, byte change, raw import) so it doesn't even open in UABE after saving and loading.
